### ISSUE TITLE
Strict pragmas in interfaces

### ISSUE THREAD

**Issue by klkvr** [cryptoalgebra/Algebra#66]
It would be really convenient if interfaces in tokenomics section were having non-strict pragmas (e. g. `pragma solidity >=0.8.0` instead of current `pragma solidity =0.8.17`). Right now it's impossible to load this repo as a foundry lib and use interfaces in contracts for projects using different versions

It would be great if you could update it in other branches too, because as i understand, quickswap runs on 1.1.0 version or lower

**Comment by klkvr** [comment]
By the way, having a commit hash [here](https://docs.algebra.finance/en/docs/contracts/partners/introduction) indicating which contracts are deployed for each project would be great.

**Comment by vladyan18** [comment]
Hello! Thanks for the feedback! 
I think that we will publish separate packages with interfaces, we will change the pragmas there. I note that custom errors are defined in some interfaces, so the restriction on the minimum version will remain.

At the link you provided, you can find links to commits or corresponding branches. You need to click on the name of the corresponding protocol.

**Comment by klkvr** [comment]
Oh, I missed that part on the website, thanks! Please close this issue once the repo with interfaces will be published

**Comment by IliaAzhel** [comment]
Thanks for reporting! The patched farming packages can now be found in the respective repositories.
